import type { SellerConfig } from "./seller-config.types";

export const demoSellerConfigs: SellerConfig[] = [
  {
    sellerId: "seller_demo_sandals",
    businessName: "Demo Sandals Store",
    languageStyle: "darija",
    showPriceOnFirstReply: true,
    firstEntryPolicy: {
      enabled: true,
      showProductName: true,
      showPrice: true,
      showDelivery: true,
      showPayment: true,
      showPromotion: false,
      showTrustLine: true,
      ctaMode: "order_or_info",
      greetingStyle: "friendly",
      primaryCtaLabel: "أطلب الآن",
      secondaryCtaLabel: "المزيد من المعلومات",
    },
    deliveryPolicy: {
      enabled: true,
      availability: "all_cities",
      isFree: false,
      currency: "MAD",
      wordingStyle: "clear",
      pricing: {
        enabled: true,
        mode: "CITY_RULES",
        currency: "MAD",
        rules: [
          {
            id: "casablanca-free",
            type: "FREE",
            cityKeys: ["الدار البيضاء"],
            aliases: ["كازا", "casa", "casablanca", "الدارالبيضاء"],
            priority: 100,
          },
          {
            id: "marrakech-30",
            type: "PAID",
            amount: 30,
            cityKeys: ["مراكش"],
            aliases: ["marrakech", "marrakesh"],
            priority: 100,
          },
          {
            id: "rabat-25",
            type: "PAID",
            amount: 25,
            cityKeys: ["الرباط"],
            aliases: ["rabat"],
            priority: 100,
          },
          {
            id: "demo-unavailable-zone",
            type: "UNAVAILABLE",
            cityKeys: ["منطقة خارج التغطية"],
            aliases: ["خارج التغطية"],
            priority: 100,
          },
        ],
        defaultRule: {
          id: "other-supported-locations-35",
          type: "PAID",
          amount: 35,
        },
      },
    },
    delivery: {
      enabled: true,
      free: false,
      text: "التوصيل حتى لباب الدار",
      paymentOnDelivery: true,
      paymentText: "الدفع عند الاستلام",
    },
    customerFields: [
      {
        key: "fullName",
        label: "الاسم الكامل",
        required: true,
        enabled: true,
        askOrder: 4,
      },
      {
        key: "phone",
        label: "رقم الهاتف",
        required: true,
        enabled: true,
        askOrder: 5,
      },
      {
        key: "city",
        label: "المدينة",
        required: true,
        enabled: true,
        askOrder: 6,
      },
      {
        key: "address",
        label: "العنوان",
        required: true,
        enabled: true,
        askOrder: 7,
        captureMode: "ADDRESS",
        allowMultipleMessages: true,
      },
      {
        key: "quantity",
        label: "الكمية",
        required: true,
        enabled: true,
        askOrder: 3,
      },
    ],
    interactive: {
      firstReplyMode: "buttons",
      optionDisplayMode: "auto",
      infoMenuDisplayMode: "list",
    },
    receipt: {
      enabled: true,
      sendAfterConfirmation: true,
      showLogo: true,
      footerText: "Merci pour votre commande !",
      locale: "fr",
      currency: "MAD",
      paymentMethodLabel: "Paiement à la livraison",
      branding: {
        storeName: "Élégance Boutique",
        slogan: "Style, qualité et confiance",
        logoUrl: "src/modules/order-receipt/fixtures/demo-logo.svg",
        primaryColor: "#062E67",
        secondaryColor: "#F4F8FD",
        accentColor: "#C78A22",
        phone: "06 00 00 00 00",
        whatsapp: "06 00 00 00 00",
        email: "contact@example.com",
        address: "Marrakech, Maroc",
        instagram: "@eleganceboutique",
      },
    },
    ai: {
      mode: "hybrid",
      naturalReplyEnabled: false,
    },
  },
  {
    sellerId: "seller_demo_medical",
    businessName: "Demo Medical Store",
    languageStyle: "darija",
    showPriceOnFirstReply: true,
    firstEntryPolicy: {
      enabled: true,
      showProductName: true,
      showPrice: true,
      showDelivery: true,
      showPayment: true,
      showPromotion: false,
      showTrustLine: true,
      ctaMode: "order_or_info",
      greetingStyle: "professional",
      primaryCtaLabel: "أطلب الآن",
      secondaryCtaLabel: "المزيد من المعلومات",
    },
    deliveryPolicy: {
      enabled: true,
      availability: "selected_cities",
      isFree: false,
      deliveryPrice: 25,
      currency: "MAD",
      cities: ["الدار البيضاء", "الرباط", "مراكش", "فاس"],
      wordingStyle: "professional",
      pricing: {
        enabled: true,
        mode: "FLAT_RATE",
        flatRate: 25,
        currency: "MAD",
      },
    },
    delivery: {
      enabled: true,
      free: false,
      text: "التوصيل متوفر حتى لباب الدار",
      deliveryPrice: 25,
      paymentOnDelivery: true,
      paymentText: "الدفع عند الاستلام",
    },
    customerFields: [
      {
        key: "fullName",
        label: "الاسم الكامل",
        required: true,
        enabled: true,
        askOrder: 1,
      },
      {
        key: "phone",
        label: "رقم الهاتف",
        required: true,
        enabled: true,
        askOrder: 2,
      },
      {
        key: "city",
        label: "المدينة",
        required: true,
        enabled: true,
        askOrder: 3,
      },
      {
        key: "address",
        label: "العنوان",
        required: false,
        enabled: false,
        askOrder: 4,
      },
    ],
    interactive: {
      firstReplyMode: "buttons",
      optionDisplayMode: "auto",
      infoMenuDisplayMode: "list",
    },
    receipt: {
      enabled: true,
      sendAfterConfirmation: true,
      showLogo: true,
      footerText: "Merci pour votre commande !",
      locale: "fr",
      currency: "MAD",
      paymentMethodLabel: "Paiement à la livraison",
    },
    ai: {
      mode: "hybrid",
      naturalReplyEnabled: false,
    },
  },
  {
    sellerId: "seller_demo_not_mentioned",
    businessName: "Demo General Store",
    languageStyle: "darija",
    showPriceOnFirstReply: false,
    firstEntryPolicy: {
      enabled: true,
      showProductName: true,
      showPrice: false,
      showDelivery: false,
      showPayment: false,
      showPromotion: false,
      showTrustLine: false,
      ctaMode: "info_only",
      greetingStyle: "short",
      primaryCtaLabel: "أطلب الآن",
      secondaryCtaLabel: "المزيد من المعلومات",
    },
    deliveryPolicy: {
      enabled: false,
      availability: "not_mentioned",
      isFree: false,
      currency: "MAD",
      wordingStyle: "short",
      pricing: {
        enabled: true,
        mode: "ALL_FREE",
        currency: "MAD",
      },
    },
    delivery: {
      enabled: false,
      free: false,
      text: "",
      paymentOnDelivery: false,
      paymentText: "",
    },
    customerFields: [
      {
        key: "fullName",
        label: "الاسم الكامل",
        required: true,
        enabled: true,
        askOrder: 1,
      },
      {
        key: "phone",
        label: "رقم الهاتف",
        required: true,
        enabled: true,
        askOrder: 2,
      },
      {
        key: "city",
        label: "المدينة",
        required: true,
        enabled: true,
        askOrder: 3,
      },
    ],
    interactive: {
      firstReplyMode: "text",
      optionDisplayMode: "text",
      infoMenuDisplayMode: "text",
    },
    receipt: {
      enabled: false,
      sendAfterConfirmation: false,
    },
    ai: {
      mode: "direct",
      naturalReplyEnabled: false,
    },
  },
];
