import { randomUUID } from "node:crypto";
import dotenv from "dotenv";
import { closeDatabasePool, createTenantContext, executeDatabaseQuery, runDatabaseMigrations } from "../../../../infrastructure/database";
import { SellerCommerceRuntimeProjectionReader } from "../../../../composition/runtime-read/seller-commerce-runtime-projection";
import { CatalogService, PostgreSqlCatalogRepository } from "../../../catalog";
import { ConversationConfigService, PostgreSqlConversationConfigRepository } from "../../../conversation-config";
import { SellerService } from "../../../seller/application/seller.service";
import { PostgreSqlSellerRepository } from "../../../seller/infrastructure/postgresql/postgresql-seller.repository";
import { PostgreSqlSellerWorkspaceProfileRepository } from "../../../seller-workspace-profile";
import { SellerCommerceConfigRepository, SellerCommerceConfigRuntimeReader } from "../../../seller-commerce-config";
import { PostgreSqlWhatsAppConnectionRepository, WhatsAppConnectionProductBindingService } from "../../../whatsapp-connection";
import { createCartItem, hydrateCartProductAuthority } from "../cart-state.service";
import type { CartDraft } from "../cart-state.types";
import { calculateSelectedOfferPricing, calculateStandardCartPricing, evaluateAllEligibleOffers } from "../pricing/cart-pricing.service";
import { revalidateCartBeforeConfirmation } from "../confirmation-revalidation.service";
import { runCartReviewPreview } from "../cart-review/cart-review-preview.service";

dotenv.config();
type TestCase = Readonly<{ name: string; passed: boolean }>;
const cases: TestCase[] = []; const sellers: string[] = [];
const add = (name: string, passed: boolean) => cases.push({ name, passed });
const id = (prefix: string) => `${prefix}_${randomUUID().replace(/-/gu, "")}`;
const now = new Date("2026-08-05T12:00:00.000Z");
function config(sellerId: string) { return { configVersion: 1, payment: { method: "COD", enabled: true }, delivery: { enabled: true, availability: "all_cities", pricing: { mode: "ALL_FREE", currency: "MAD" } }, requiredCustomerFields: [{ key: "fullName", label: "Name", required: true, enabled: true }], orderBehavior: { multiItemOrderFlow: { enabled: true, runtimeMode: "guarded", allowedSellerIds: [sellerId] } }, receipt: { enabled: true, sendAfterConfirmation: true } }; }
function catalogProduct(productId: string, price = 19_999, availability: "available" | "unavailable" = "available", offers = true) { return { productId, name: "Catalog lantern", description: "Dynamic Catalog authority", price: { amountMinor: price, currencyCode: "MAD" }, availability, options: [{ optionId: "finish-id", label: "Finish", required: true, position: 0, values: [{ valueId: "matte-id", label: "Matte", position: 0, isAvailable: true }, { valueId: "gloss-id", label: "Gloss", position: 1, isAvailable: true }, { valueId: "retired-id", label: "Retired", position: 2, isAvailable: false }] }], images: [], aliases: [], offers: offers ? [{ offerId: "bundle-z", label: "Inactive", requiredItemCount: 2, totalPriceAmountMinor: 30_000, active: false, allowMixedOptions: true, priority: 0 }, { offerId: "bundle-b", label: "Catalog bundle B", requiredItemCount: 2, totalPriceAmountMinor: 35_000, active: true, allowMixedOptions: false, priority: 2 }, { offerId: "bundle-a", label: "Catalog bundle A", requiredItemCount: 2, totalPriceAmountMinor: 34_000, active: true, allowMixedOptions: false, priority: 1 }, { offerId: "future", label: "Future", requiredItemCount: 2, totalPriceAmountMinor: 30_000, active: true, allowMixedOptions: true, priority: 0, startsAt: "2026-09-01T00:00:00.000Z" }, { offerId: "expired", label: "Expired", requiredItemCount: 2, totalPriceAmountMinor: 30_000, active: true, allowMixedOptions: true, priority: 0, endsAt: "2026-08-01T00:00:00.000Z" }, { offerId: "over", label: "Over", requiredItemCount: 2, totalPriceAmountMinor: 50_000, active: true, allowMixedOptions: true, priority: 0 } ] : [] }; }
function cart(productId: string, option = "Matte", quantity = 2): CartDraft { return { schemaVersion: 1, mode: "STANDARD", status: "AWAITING_CONFIRMATION", items: [createCartItem({ id: "line-1", productId, quantity, selectedOptions: { "finish-id": option }, status: "COMPLETE" })], orderLevelFields: { fullName: "Amina" } }; }
async function cleanup() { if (!sellers.length) return; await executeDatabaseQuery({ text: "DELETE FROM whatsapp_connections WHERE seller_id = ANY($1::varchar[])", values: [sellers] }); await executeDatabaseQuery({ text: "DELETE FROM seller_conversation_configs WHERE seller_id = ANY($1::varchar[])", values: [sellers] }); await executeDatabaseQuery({ text: "DELETE FROM seller_commerce_configs WHERE seller_id = ANY($1::varchar[])", values: [sellers] }); await executeDatabaseQuery({ text: "DELETE FROM seller_workspace_profiles WHERE seller_id = ANY($1::varchar[])", values: [sellers] }); await executeDatabaseQuery({ text: "DELETE FROM products WHERE seller_id = ANY($1::varchar[])", values: [sellers] }); await executeDatabaseQuery({ text: "DELETE FROM sellers WHERE seller_id = ANY($1::varchar[])", values: [sellers] }); }

async function main() {
  await closeDatabasePool(); const sellerService = new SellerService(new PostgreSqlSellerRepository()); const catalog = new CatalogService(new PostgreSqlCatalogRepository()); const conversations = new ConversationConfigService(new PostgreSqlConversationConfigRepository()); const commerce = new SellerCommerceConfigRepository(); const profiles = new PostgreSqlSellerWorkspaceProfileRepository(); const connections = new PostgreSqlWhatsAppConnectionRepository(); const binding = new WhatsAppConnectionProductBindingService(connections, catalog); const reader = new SellerCommerceRuntimeProjectionReader({ commerceConfigReader: new SellerCommerceConfigRuntimeReader(commerce), catalogService: catalog, conversationConfigService: conversations, workspaceProfileRepository: profiles, whatsappConnectionRepository: connections });
  const sellerA = id("seller_d4_b3_2_a"), sellerB = id("seller_d4_b3_2_b"), productId = id("product"), foreignProductId = productId; sellers.push(sellerA, sellerB); const tenantA = createTenantContext(sellerA), tenantB = createTenantContext(sellerB);
  try {
    const migrations = await runDatabaseMigrations(); add("PostgreSQL migrations are available for focused runtime acceptance", migrations.pending.length === 0);
    for (const [seller, tenant] of [[sellerA, tenantA], [sellerB, tenantB]] as const) { await sellerService.createSeller(seller); await profiles.createProfile({ sellerId: seller, displayName: "Cart authority store" }); await commerce.save(tenant, config(seller)); await conversations.saveSellerOverride(tenant, { schemaVersion: 1 }); }
    await catalog.createProduct(tenantA, catalogProduct(productId)); await catalog.createProduct(tenantB, catalogProduct(foreignProductId, 9_999));
    const connection = await connections.createCandidate(tenantA); await connections.persistVerifiedMetadata(tenantA, connection.connectionId, { metaBusinessId: id("business"), wabaId: id("waba"), phoneNumberId: id("phone"), displayPhoneNumber: "+212600000001", verifiedName: "Authority" }); await connections.updateLifecycleStatus(tenantA, connection.connectionId, "ACTIVE"); await binding.setBoundProductId(tenantA, connection.connectionId, productId);
    const connectionB = await connections.createCandidate(tenantB); await connections.persistVerifiedMetadata(tenantB, connectionB.connectionId, { metaBusinessId: id("business"), wabaId: id("waba"), phoneNumberId: id("phone"), displayPhoneNumber: "+212600000002", verifiedName: "Foreign authority" }); await connections.updateLifecycleStatus(tenantB, connectionB.connectionId, "ACTIVE"); await binding.setBoundProductId(tenantB, connectionB.connectionId, foreignProductId);
    const resolved = await reader.resolve({ sellerId: sellerA, connectionId: connection.connectionId }); add("real connection-bound PostgreSQL runtime projection resolves Catalog authority", resolved.status === "READY" && resolved.productContext.productId === productId && resolved.productContext.priceAmountMinor === 19_999);
    if (resolved.status !== "READY") throw new Error("bound runtime projection unavailable"); const context = resolved.productContext;
    add("Catalog runtime projection carries fixed-bundle offers and stable dynamic option IDs", context.offers?.some((offer) => offer.id === "bundle-a" && offer.totalPriceAmountMinor === 34_000) === true && context.optionGroups[0]?.key === "finish-id" && context.optionGroups[0]?.valueConfigurations?.[0]?.key === "matte-id");
    const hydrated = hydrateCartProductAuthority({ cart: cart(productId), productContext: context }); const line = hydrated.cart.items[0]!;
    add("cart freezes product identity, name, minor price and root currency", hydrated.valid && line.productId === productId && line.productName === context.name && line.unitPriceAmountMinor === 19_999 && line.currencyCode === "MAD");
    add("cart stores option and value IDs alongside authoritative labels", line.selectedOptionFacts?.[0]?.optionId === "finish-id" && line.selectedOptionFacts?.[0]?.valueId === "matte-id" && line.selectedOptionFacts?.[0]?.optionLabel === "Finish" && line.selectedOptionFacts?.[0]?.valueLabel === "Matte");
    add("unavailable and fabricated option labels fail closed", !hydrateCartProductAuthority({ cart: cart(productId, "Retired"), productContext: context }).valid && !hydrateCartProductAuthority({ cart: cart(productId, "Fabricated"), productContext: context }).valid);
    add("foreign product cannot enter the bound cart", !hydrateCartProductAuthority({ cart: cart("foreign-product-id"), productContext: context }).valid);
    const standard = calculateStandardCartPricing({ sellerId: sellerA, productContext: context, cart: hydrated.cart, now }); add("minor-unit quantity multiplication is exact without decimal drift", standard.ok && standard.quote?.normalSubtotalAmountMinor === 39_998 && standard.quote.finalTotalAmountMinor === 39_998 && standard.quote.lines[0]?.lineSubtotalAmountMinor === 39_998);
    const all = evaluateAllEligibleOffers({ sellerId: sellerA, productContext: context, cart: hydrated.cart, now }); add("Catalog fixed bundles select deterministic lower-priority offer", all.recommendedOffer?.offer.id === "bundle-a" && all.recommendedOffer?.quote?.finalTotalAmountMinor === 34_000 && all.recommendedOffer?.quote?.discountAmountMinor === 5_998);
    add("inactive future expired and above-subtotal offers are never eligible", !all.eligibleOffers.some((item) => ["bundle-z", "future", "expired", "over"].includes(item.offer.id)));
    add("non-exact bundle quantities and mixed options are rejected", !calculateSelectedOfferPricing({ sellerId: sellerA, productContext: context, cart: hydrateCartProductAuthority({ cart: cart(productId, "Matte", 1), productContext: context }).cart, offerId: "bundle-a", now }).quote && !calculateSelectedOfferPricing({ sellerId: sellerA, productContext: context, cart: hydrateCartProductAuthority({ cart: { ...cart(productId), items: [createCartItem({ id: "a", productId, quantity: 1, selectedOptions: { "finish-id": "Matte" }, status: "COMPLETE" }), createCartItem({ id: "b", productId, quantity: 1, selectedOptions: { "finish-id": "Gloss" }, status: "COMPLETE" })] }, productContext: context }).cart, offerId: "bundle-a", now }).quote);
    add("foreign offer IDs and legacy decimal price cannot alter connected Catalog totals", !calculateSelectedOfferPricing({ sellerId: sellerA, productContext: context, cart: hydrated.cart, offerId: "foreign-offer", now }).quote && calculateStandardCartPricing({ sellerId: sellerA, productContext: { ...context, price: 1.11 }, cart: hydrated.cart, now }).quote?.finalTotalAmountMinor === 39_998);
    add("unsafe authoritative money fails closed", !calculateStandardCartPricing({ sellerId: sellerA, productContext: { ...context, priceAmountMinor: Number.MAX_SAFE_INTEGER + 1 }, cart: hydrated.cart, now }).ok);
    const review = runCartReviewPreview({ previewEnabled: true, sellerId: sellerA, productContext: context, requiredFields: [], offerLookup: { state: "OFFERS_CONFIGURED", sellerId: sellerA, productId, offers: context.offers || [], activeOffers: (context.offers || []).filter((offer) => offer.active), validation: { valid: true, normalizedOffers: context.offers || [], errors: [], warnings: [] } }, cart: { ...hydrated.cart, status: "CART_REVIEW", targetItemCount: 2 }, now }); add("existing cart-review runtime seam consumes Catalog commercial authority", review.handled && review.success && review.commercialEvaluation?.recommendedOffer?.offerId === "bundle-a");
    const initial = revalidateCartBeforeConfirmation({ cart: hydrated.cart, expectedProductId: productId, sellerId: sellerA, productContext: context, fields: [], now }); add("unchanged bound product creates a review fingerprint and can confirm", initial.status === "UNCHANGED" && Boolean(initial.cart.reviewFingerprint));
    const same = revalidateCartBeforeConfirmation({ cart: initial.cart, expectedProductId: productId, sellerId: sellerA, productContext: context, fields: [], now }); add("unchanged revalidation preserves valid confirmation", same.status === "UNCHANGED");
    await catalog.replaceProduct(tenantA, catalogProduct(productId, 21_000)); const changed = await reader.resolve({ sellerId: sellerA, connectionId: connection.connectionId }); if (changed.status !== "READY") throw new Error("changed product unavailable"); const priceChanged = revalidateCartBeforeConfirmation({ cart: initial.cart, expectedProductId: productId, sellerId: sellerA, productContext: changed.productContext, fields: [], now }); add("price change requires a new review and updates temporary minor facts", priceChanged.status === "REVIEW_REQUIRED" && priceChanged.cart.items[0]?.unitPriceAmountMinor === 21_000);
    const removedOptionProduct = catalogProduct(productId, 21_000); removedOptionProduct.options[0]!.values = removedOptionProduct.options[0]!.values.filter((value) => value.valueId !== "matte-id"); await catalog.replaceProduct(tenantA, removedOptionProduct); const removedOption = await reader.resolve({ sellerId: sellerA, connectionId: connection.connectionId }); if (removedOption.status !== "READY") throw new Error("option change unavailable"); add("removed option value requires correction and never confirms silently", revalidateCartBeforeConfirmation({ cart: initial.cart, expectedProductId: productId, sellerId: sellerA, productContext: removedOption.productContext, fields: [], now }).status === "CORRECTION_REQUIRED");
    await catalog.replaceProduct(tenantA, catalogProduct(productId, 21_000));
    await catalog.replaceProduct(tenantA, catalogProduct(productId, 21_000, "available", false)); const noOffers = await reader.resolve({ sellerId: sellerA, connectionId: connection.connectionId }); if (noOffers.status !== "READY") throw new Error("offer change unavailable"); const offerChanged = revalidateCartBeforeConfirmation({ cart: priceChanged.cart, expectedProductId: productId, sellerId: sellerA, productContext: noOffers.productContext, fields: [], now }); add("offer removal requires a new review rather than silently confirming", offerChanged.status === "REVIEW_REQUIRED");
    await catalog.setProductAvailability(tenantA, productId, "unavailable"); const unavailable = await reader.resolve({ sellerId: sellerA, connectionId: connection.connectionId }); add("unavailable product blocks confirmation", unavailable.status !== "READY" && revalidateCartBeforeConfirmation({ cart: initial.cart, expectedProductId: productId, sellerId: sellerA, productContext: undefined, fields: [], now }).status === "BLOCKED");
    await catalog.setProductAvailability(tenantA, productId, "available"); await binding.setBoundProductId(tenantA, connection.connectionId, null); const rebound = await reader.resolve({ sellerId: sellerA, connectionId: connection.connectionId }); add("binding removal blocks an old-product cart with no cross-product fallback", rebound.status !== "READY" && revalidateCartBeforeConfirmation({ cart: initial.cart, expectedProductId: productId, sellerId: sellerA, productContext: undefined, fields: [], now }).reason === "PRODUCT_UNAVAILABLE");
    const replacementId = id("replacement"); await catalog.createProduct(tenantA, catalogProduct(replacementId, 17_000)); await binding.setBoundProductId(tenantA, connection.connectionId, replacementId); const replacement = await reader.resolve({ sellerId: sellerA, connectionId: connection.connectionId }); add("connection binding change blocks the old cart rather than merging products", replacement.status === "READY" && revalidateCartBeforeConfirmation({ cart: initial.cart, expectedProductId: productId, sellerId: sellerA, productContext: replacement.productContext, fields: [], now }).reason === "BINDING_CHANGED");
    await binding.setBoundProductId(tenantA, connection.connectionId, productId); await executeDatabaseQuery({ text: "DELETE FROM products WHERE seller_id = $1 AND product_id = $2", values: [sellerA, productId] }); const deleted = await reader.resolve({ sellerId: sellerA, connectionId: connection.connectionId }); add("product deletion clears the binding and blocks confirmation", deleted.status !== "READY" && (await connections.findByConnectionId(tenantA, connection.connectionId))?.boundProductId === null && revalidateCartBeforeConfirmation({ cart: initial.cart, expectedProductId: productId, sellerId: sellerA, productContext: undefined, fields: [], now }).status === "BLOCKED");
    const foreign = await reader.resolve({ sellerId: sellerB, connectionId: connectionB.connectionId }); add("same product IDs under different sellers remain isolated", foreign.status === "READY" && foreign.productContext.sellerId === sellerB && foreign.productContext.priceAmountMinor === 9_999);
  } finally { await cleanup(); const remaining = await executeDatabaseQuery<{ count: string }>({ text: "SELECT COUNT(*)::text AS count FROM sellers WHERE seller_id = ANY($1::varchar[])", values: [sellers] }); add("focused PostgreSQL rows are cleaned up", remaining.rows[0]?.count === "0"); await closeDatabasePool(); }
  const failed = cases.filter((entry) => !entry.passed); process.stdout.write(`${JSON.stringify({ phase: "D4-B3.2", summary: { total: cases.length, passed: cases.length - failed.length, failed: failed.length }, cases }, null, 2)}\n`); process.exitCode = failed.length ? 1 : 0;
}
main().catch(async () => { await closeDatabasePool(); process.stderr.write('{"phase":"D4-B3.2","ok":false,"message":"cart pricing authority acceptance failed safely"}\n'); process.exitCode = 1; });
