import { randomUUID } from "node:crypto";
import dotenv from "dotenv";
import { closeDatabasePool, createTenantContext, executeDatabaseQuery, runDatabaseMigrations } from "../../../../infrastructure/database";
import { SellerService } from "../../../seller/application/seller.service";
import { PostgreSqlSellerRepository } from "../../../seller/infrastructure/postgresql/postgresql-seller.repository";
import { CatalogService, PostgreSqlCatalogRepository } from "../../../catalog";
import { PostgreSqlWhatsAppConnectionRepository, WhatsAppConnectionProductBindingService } from "../../../whatsapp-connection";
import { ConfirmedOrderPersistenceService } from "../persistence/application/confirmed-order-persistence.service";
import { PostgreSqlConfirmedOrderRepository } from "../persistence/infrastructure/postgresql/postgresql-confirmed-order.repository";
import { buildConfirmedOrderReceiptModel, generateConfirmedOrderReceiptPreviewPdf } from "../confirmed-order/confirmed-order-receipt.service";
import type { ConfirmedOrderSnapshot } from "../confirmed-order/confirmed-order-snapshot.types";
dotenv.config();
type Case = { name: string; passed: boolean }; const cases: Case[] = []; const add = (name: string, passed: boolean) => cases.push({ name, passed }); const id = (prefix: string) => `${prefix}_${randomUUID().replace(/-/g, "")}`; function freeze<T>(value: T): T { if (value && typeof value === "object" && !Object.isFrozen(value)) { for (const child of Object.values(value as Record<string, unknown>)) freeze(child); Object.freeze(value); } return value; }
function product(productId: string, name = "Historic product", price = 20_000) { return { productId, name, price: { amountMinor: price, currencyCode: "MAD" }, availability: "available" as const, options: [{ optionId: "finish", label: "Finish", required: true, position: 0, values: [{ valueId: "matte", label: "Matte", position: 0, isAvailable: true }] }], images: [], aliases: [], offers: [{ offerId: "bundle", label: "Two pack", requiredItemCount: 2, totalPriceAmountMinor: 35_000, active: true, allowMixedOptions: false }] }; }
function snapshot(sellerId: string, orderId: string, productId: string): ConfirmedOrderSnapshot { return { schemaVersion: 1, id: orderId, sellerId, conversationScopeId: "scope", confirmedAt: "2026-08-05T12:00:00.000Z", product: { productId, name: "Historic product" }, receiptContext: { storeName: "Historic Store", productImageRef: "missing-optional-image" }, items: [{ itemId: "line", productId, productName: "Historic product", quantity: 2, selectedOptions: [{ key: "finish", label: "Finish", value: "Matte", optionId: "finish", optionLabel: "Finish", valueId: "matte", valueLabel: "Matte" }], unitPriceMinor: 20_000, currencyCode: "MAD", lineSubtotalMinor: 40_000, lineDiscountMinor: 5_000, lineTotalMinor: 35_000, unitPrice: 200, lineTotal: 350 }], completedUnits: 2, targetUnits: 2, orderFields: [{ key: "fullName", label: "Name", value: "Amina" }], currency: "MAD", standardSubtotalMinor: 40_000, subtotalAmountMinor: 40_000, discountAmountMinor: 5_000, standardSubtotal: 400, selectedOffer: { offerId: "bundle", label: "Two pack", normalSubtotalMinor: 40_000, offerTotalMinor: 35_000, discountMinor: 5_000, offerTotal: 350, discountAmount: 50 }, merchandiseTotalMinor: 35_000, merchandiseTotal: 350, finalTotalMinor: 35_000, totalAmountMinor: 35_000, finalTotal: 350, commercialWarnings: [] }; }
async function main() {
  await closeDatabasePool(); const sellerA = id("seller_snap_a"), sellerB = id("seller_snap_b"), productId = "shared-product", orderId = id("order"); const tenantA = createTenantContext(sellerA), tenantB = createTenantContext(sellerB); const sellerService = new SellerService(new PostgreSqlSellerRepository()); const catalog = new CatalogService(new PostgreSqlCatalogRepository()); const connections = new PostgreSqlWhatsAppConnectionRepository(); const orders = new ConfirmedOrderPersistenceService(new PostgreSqlConfirmedOrderRepository());
  try {
    const migrations = await runDatabaseMigrations(); add("PostgreSQL migrations are current", migrations.pending.length === 0);
    for (const [seller, tenant] of [[sellerA, tenantA], [sellerB, tenantB]] as const) { await sellerService.createSeller(seller); await catalog.createProduct(tenant, product(productId, seller === sellerA ? "Historic product" : "Foreign product", seller === sellerA ? 20_000 : 9_999)); }
    const connection = await connections.createCandidate(tenantA); await new WhatsAppConnectionProductBindingService(connections, catalog).setBoundProductId(tenantA, connection.connectionId, productId);
    const source = snapshot(sellerA, orderId, productId); (source.orderFields as Array<unknown>).push({ key: "phone", label: "Phone", value: "0612345678" }); const frozenSource = freeze(source); const persisted = await orders.persistConfirmedOrder(tenantA, { snapshot: frozenSource, confirmationIdempotencyKey: "confirm" });
    add("order and immutable snapshot persist atomically", persisted.orderId === orderId && persisted.snapshot.id === orderId);
    const line = persisted.snapshot.items[0]!;
    add("snapshot retains IDs labels offer facts and exact minor amounts", line.selectedOptions[0]?.optionId === "finish" && line.selectedOptions[0]?.valueId === "matte" && line.lineSubtotalMinor === 40_000 && line.lineDiscountMinor === 5_000 && line.lineTotalMinor === 35_000 && persisted.snapshot.selectedOffer?.offerId === "bundle" && persisted.snapshot.discountAmountMinor === 5_000);
    const before = buildConfirmedOrderReceiptModel(persisted.snapshot); add("receipt authority is the persisted immutable snapshot", before.success && before.receiptModel?.lines[0]?.productName === "Historic product" && before.receiptModel?.selectedOffer?.discountAmount === 50);
    await catalog.replaceProduct(tenantA, product(productId, "Renamed mutable product", 99_999)); await executeDatabaseQuery({ text: "DELETE FROM products WHERE seller_id = $1 AND product_id = $2", values: [sellerA, productId] }); const stored = await orders.getConfirmedOrderSnapshot(tenantA, orderId); const after = stored && buildConfirmedOrderReceiptModel(stored);
    add("Catalog mutation deletion and cleared binding cannot alter historical receipt", (await connections.findByConnectionId(tenantA, connection.connectionId))?.boundProductId === null && after?.success === true && JSON.stringify(before.receiptModel) === JSON.stringify(after.receiptModel));
    add("optional unavailable image does not block receipt generation", Boolean(after?.receiptModel && (await generateConfirmedOrderReceiptPreviewPdf(after.receiptModel)).success));
    add("duplicate confirmation remains idempotent", (await orders.persistConfirmedOrder(tenantA, { snapshot: frozenSource, confirmationIdempotencyKey: "confirm" })).orderId === orderId);
    add("foreign seller cannot load receipt snapshot", await orders.getConfirmedOrderSnapshot(tenantB, orderId) === null);
    const legacy: ConfirmedOrderSnapshot = { ...source, id: id("legacy"), items: [{ ...line, selectedOptions: [{ key: "finish", label: "Old finish", value: "Old matte" }] }] }; const legacyReceipt = buildConfirmedOrderReceiptModel(legacy);
    add("legacy snapshot remains receipt-compatible without newer IDs", legacyReceipt.success && legacyReceipt.receiptModel?.lines[0]?.options[0]?.label === "Old finish");
    add("line and order money reconcile exactly", line.lineSubtotalMinor! - line.lineDiscountMinor! === line.lineTotalMinor && persisted.snapshot.standardSubtotalMinor - persisted.snapshot.discountAmountMinor! === persisted.snapshot.finalTotalMinor);
  } finally {
    await executeDatabaseQuery({ text: "DELETE FROM whatsapp_connections WHERE seller_id = ANY($1::varchar[])", values: [[sellerA, sellerB]] }); await executeDatabaseQuery({ text: "DELETE FROM orders WHERE seller_id = ANY($1::varchar[])", values: [[sellerA, sellerB]] }); await executeDatabaseQuery({ text: "DELETE FROM products WHERE seller_id = ANY($1::varchar[])", values: [[sellerA, sellerB]] }); await executeDatabaseQuery({ text: "DELETE FROM sellers WHERE seller_id = ANY($1::varchar[])", values: [[sellerA, sellerB]] }); await closeDatabasePool();
  }
  const failed = cases.filter((entry) => !entry.passed); process.stdout.write(`${JSON.stringify({ phase: "D4-B3.3", summary: { total: cases.length, passed: cases.length - failed.length, failed: failed.length }, cases }, null, 2)}\n`); process.exitCode = failed.length ? 1 : 0;
}
main().catch(async (error: unknown) => { await closeDatabasePool(); process.stderr.write(`${JSON.stringify({ phase: "D4-B3.3", ok: false, message: error instanceof Error ? error.message : "acceptance failed" })}\n`); process.exitCode = 1; });
