import type { SellerConfig } from "../agent/config/seller-config.types";
import { parseSellerCommerceConfig } from "./seller-commerce-config.parser";
import type { SellerCommerceConfigV1 } from "./seller-commerce-config.types";

const majorToMinor = (value: number | undefined): number | undefined => value === undefined ? undefined : Math.round(value * 100);
export function canonicalSellerCommerceConfigFromLegacy(config: SellerConfig): SellerCommerceConfigV1 {
  const pricing = config.deliveryPolicy.pricing;
  return parseSellerCommerceConfig({ configVersion: 1, payment: { method: "COD", enabled: config.delivery.paymentOnDelivery }, delivery: { enabled: config.delivery.enabled, availability: config.deliveryPolicy.availability, pricing: { mode: pricing?.mode || (config.delivery.free ? "ALL_FREE" : "FLAT_RATE"), currency: "MAD", ...(pricing?.flatRate !== undefined ? { flatRateMinor: majorToMinor(pricing.flatRate) } : config.delivery.deliveryPrice !== undefined ? { flatRateMinor: majorToMinor(config.delivery.deliveryPrice) } : {}), ...(pricing?.rules ? { rules: pricing.rules.map(({ amount, ...rule }) => ({ ...rule, ...(amount !== undefined ? { amountMinor: majorToMinor(amount) } : {}) })) } : {}), ...(pricing?.defaultRule ? { defaultRule: (() => { const { amount, ...rule } = pricing.defaultRule!; return { ...rule, ...(amount !== undefined ? { amountMinor: majorToMinor(amount) } : {}) }; })() } : {}) } }, requiredCustomerFields: config.customerFields, orderBehavior: { multiItemOrderFlow: config.multiItemOrderFlow || { enabled: false, runtimeMode: "disabled", allowedSellerIds: [] } }, receipt: { enabled: config.receipt.enabled, sendAfterConfirmation: config.receipt.sendAfterConfirmation, ...(config.receipt.showLogo !== undefined ? { showLogo: config.receipt.showLogo } : {}), ...(config.receipt.footerText ? { footerText: config.receipt.footerText } : {}), ...(config.receipt.paymentMethodLabel ? { paymentMethodLabel: config.receipt.paymentMethodLabel } : {}) } });
}
