import { randomUUID } from "node:crypto";
import dotenv from "dotenv";
import { closeDatabasePool, createTenantContext, executeDatabaseQuery, getDatabaseMigrationStatus, getDatabasePoolState, runDatabaseMigrations } from "../../../../../infrastructure/database";
import { SellerService } from "../../../../seller/application/seller.service";
import { PostgreSqlSellerRepository } from "../../../../seller/infrastructure/postgresql/postgresql-seller.repository";
import { buildConfirmedOrderReceiptModel } from "../../confirmed-order/confirmed-order-receipt.service";
import type { ConfirmedOrderSnapshot } from "../../confirmed-order/confirmed-order-snapshot.types";
import { ConfirmedOrderPersistenceService } from "../application/confirmed-order-persistence.service";
import { ConfirmedOrderValidationError, OrderAlreadyExistsError, OrderIdempotencyConflictError, OrderPersistenceError, OrderSellerNotFoundError } from "../domain/order-persistence.errors";
import { PostgreSqlConfirmedOrderRepository } from "../infrastructure/postgresql/postgresql-confirmed-order.repository";

dotenv.config();
type TestCase = Readonly<{ name: string; passed: boolean }>;
const cases: TestCase[] = []; const sellerIds: string[] = [];
const add = (name: string, passed: boolean) => cases.push({ name, passed });
const unique = (prefix: string) => `${prefix}_${randomUUID().replace(/-/gu, "")}`;
function freeze<T>(value: T): T { if (!value || typeof value !== "object" || Object.isFrozen(value)) return value; for (const child of Object.values(value as Record<string, unknown>)) freeze(child); return Object.freeze(value); }
function snapshot(sellerId: string, id: string, phone = "0612345678", items = 2): ConfirmedOrderSnapshot {
  const lines = Array.from({ length: items }, (_, index) => ({ itemId: `item_${index}`, productId: `historical_product_${index}`, productName: `Produit ${index}`, quantity: 1, selectedOptions: [{ key: "material", label: "Matiere", value: index ? "Cuir" : "Toile" }, { key: "color", label: "Couleur", value: index ? "Noir" : "Rose" }], unitPriceMinor: 10_000, lineTotalMinor: 10_000, unitPrice: 100, lineTotal: 100 }));
  const total = items * 10_000 + 1_500;
  return freeze({ schemaVersion: 1, id, sellerId, conversationScopeId: `scope_${id}`, confirmedAt: "2026-07-22T12:00:00.000Z", product: { productId: "historical_product_0", name: "Produit 0" }, receiptContext: { storeName: "Boutique" }, items: lines, completedUnits: items, targetUnits: items, orderFields: [{ key: "fullName", label: "Nom", value: "Omar" }, { key: "phone", label: "Telephone", value: phone }, { key: "city", label: "Ville", value: "Marrakech" }, { key: "address", label: "Adresse", value: "Hay Salam" }], currency: "MAD", standardSubtotalMinor: items * 10_000, standardSubtotal: items * 100, merchandiseTotalMinor: items * 10_000, merchandiseTotal: items * 100, deliveryFee: { type: "PAID", amountMinor: 1_500, amount: 15, currency: "MAD" }, finalTotalMinor: total, finalTotal: total / 100, commercialWarnings: [] } as ConfirmedOrderSnapshot);
}
async function error(callback: () => Promise<unknown>, expected: new () => Error): Promise<boolean> { try { await callback(); return false; } catch (value) { return value instanceof expected; } }
async function cleanup(): Promise<void> { if (!sellerIds.length) return; await executeDatabaseQuery({ text: "DELETE FROM orders WHERE seller_id = ANY($1::varchar[])", values: [sellerIds] }); await executeDatabaseQuery({ text: "DELETE FROM sellers WHERE seller_id = ANY($1::varchar[])", values: [sellerIds] }); }

async function main(): Promise<void> {
  await closeDatabasePool(); add("Order persistence module import does not initialize PostgreSQL", !getDatabasePoolState().initialized);
  const sellers = new SellerService(new PostgreSqlSellerRepository()); const repository = new PostgreSqlConfirmedOrderRepository(); const service = new ConfirmedOrderPersistenceService(repository);
  const sellerA = unique("seller_phase7e"); const sellerB = unique("seller_phase7e"); const tenantA = createTenantContext(sellerA); const tenantB = createTenantContext(sellerB); const orderId = unique("order_phase7e");
  try {
    const invalid = snapshot(sellerA, orderId);
    add("Valid confirmed-order snapshot is accepted", buildConfirmedOrderReceiptModel(invalid).success);
    add("Missing Order ID is rejected", await error(() => service.persistConfirmedOrder(tenantA, { snapshot: freeze({ ...invalid, id: "" }), confirmationIdempotencyKey: unique("key") }), ConfirmedOrderValidationError));
    add("Blank Order ID is rejected", await error(() => service.persistConfirmedOrder(tenantA, { snapshot: freeze({ ...invalid, id: " " }), confirmationIdempotencyKey: unique("key") }), ConfirmedOrderValidationError));
    add("Overlong Order ID is rejected", await error(() => service.persistConfirmedOrder(tenantA, { snapshot: freeze({ ...invalid, id: "x".repeat(129) }), confirmationIdempotencyKey: unique("key") }), ConfirmedOrderValidationError));
    add("Missing customer phone is rejected", await error(() => service.persistConfirmedOrder(tenantA, { snapshot: freeze({ ...invalid, orderFields: invalid.orderFields.filter((field) => field.key !== "phone") }), confirmationIdempotencyKey: unique("key") }), ConfirmedOrderValidationError));
    add("Empty item list is rejected", await error(() => service.persistConfirmedOrder(tenantA, { snapshot: freeze({ ...invalid, items: [] }), confirmationIdempotencyKey: unique("key") }), ConfirmedOrderValidationError));
    add("Non-positive quantity is rejected", await error(() => service.persistConfirmedOrder(tenantA, { snapshot: freeze({ ...invalid, items: freeze([{ ...invalid.items[0]!, quantity: 0, lineTotalMinor: 0, lineTotal: 0 }]) }), confirmationIdempotencyKey: unique("key") }), ConfirmedOrderValidationError));
    add("Invalid delivery-details shape is rejected", await error(() => service.persistConfirmedOrder(tenantA, { snapshot: freeze({ ...invalid, orderFields: freeze([{ ...invalid.orderFields[0]!, value: {} as never }, ...invalid.orderFields.slice(1)] as never) }), confirmationIdempotencyKey: unique("key") }), ConfirmedOrderValidationError));
    add("Invalid selected-options shape is rejected", await error(() => service.persistConfirmedOrder(tenantA, { snapshot: freeze({ ...invalid, items: freeze([{ ...invalid.items[0]!, selectedOptions: {} as never }]) }), confirmationIdempotencyKey: unique("key") }), ConfirmedOrderValidationError));
    add("Invalid money values are rejected", await error(() => service.persistConfirmedOrder(tenantA, { snapshot: freeze({ ...invalid, finalTotalMinor: -1 }), confirmationIdempotencyKey: unique("key") }), ConfirmedOrderValidationError));
    add("Invalid currency is rejected", await error(() => service.persistConfirmedOrder(tenantA, { snapshot: freeze({ ...invalid, currency: "mad" }), confirmationIdempotencyKey: unique("key") }), ConfirmedOrderValidationError));
    const firstRun = await runDatabaseMigrations(); const secondRun = await runDatabaseMigrations(); const migration = await getDatabaseMigrationStatus(); add("Migration 0004 is applied explicitly", migration.applied.includes("0004")); add("Re-running migrations applies nothing twice", firstRun.pending.length === 0 && secondRun.applied.length === 0);
    await sellers.createSeller(sellerA); sellerIds.push(sellerA); await sellers.createSeller(sellerB); sellerIds.push(sellerB);
    const persisted = await service.persistConfirmedOrder(tenantA, { snapshot: invalid, confirmationIdempotencyKey: "key_main" });
    add("Confirmed order aggregate is persisted", persisted.orderId === orderId && persisted.status === "CONFIRMED"); add("Root order fields round-trip correctly", persisted.customerPhone === "0612345678" && persisted.totalAmountMinor === 21_500); add("Multiple items round-trip correctly", persisted.items.length === 2); add("Item order remains deterministic", persisted.items[0]?.itemId === "item_0"); add("Persisted item positions are unique and deterministic", (await executeDatabaseQuery<{ item_position: number }>({ text: "SELECT item_position FROM order_items WHERE seller_id = $1 AND order_id = $2 ORDER BY item_position", values: [sellerA, orderId] })).rows.map((row) => row.item_position).join("|") === "0|1"); add("Dynamic selected options round-trip without semantic loss", persisted.items[0]?.selectedOptions[0]?.key === "material"); add("Delivery details round-trip without semantic loss", persisted.deliveryDetails.city === "Marrakech"); add("Totals round-trip correctly", persisted.subtotalAmountMinor === 20_000 && persisted.deliveryAmountMinor === 1_500); add("Confirmed snapshot round-trips without semantic loss", persisted.snapshot.id === orderId); add("Retrieved snapshot remains deep-frozen/immutable", Object.isFrozen((await service.getConfirmedOrderSnapshot(tenantA, orderId))!)); add("Retrieved snapshot remains receipt-compatible", buildConfirmedOrderReceiptModel((await service.getConfirmedOrderSnapshot(tenantA, orderId))!).success);
    add("Unknown Order returns null", await service.getConfirmedOrder(tenantA, unique("missing")) === null); add("Unknown snapshot returns null", await service.getConfirmedOrderSnapshot(tenantA, unique("missing")) === null); add("Seller A cannot read Seller B order", await service.getConfirmedOrder(tenantB, orderId) === null);
    const orderB = snapshot(sellerB, orderId); await service.persistConfirmedOrder(tenantB, { snapshot: orderB, confirmationIdempotencyKey: "key_main" }); add("Same orderId and idempotency key may exist under different Sellers", (await service.getConfirmedOrder(tenantB, orderId))?.sellerId === sellerB);
    const retried = await service.persistConfirmedOrder(tenantA, { snapshot: invalid, confirmationIdempotencyKey: "key_main" }); add("Same-key same-payload retry returns existing Order", retried.orderId === orderId); const count = await executeDatabaseQuery<{ count: string }>({ text: "SELECT COUNT(*)::text AS count FROM order_items WHERE seller_id = $1 AND order_id = $2", values: [sellerA, orderId] }); const snapshotCount = await executeDatabaseQuery<{ count: string }>({ text: "SELECT COUNT(*)::text AS count FROM confirmed_order_snapshots WHERE seller_id = $1 AND order_id = $2", values: [sellerA, orderId] }); add("Same-key retry creates no duplicate items", count.rows[0]?.count === "2"); add("Same-key retry creates no duplicate snapshot", snapshotCount.rows[0]?.count === "1");
    add("Same key different payload returns typed conflict", await error(() => service.persistConfirmedOrder(tenantA, { snapshot: snapshot(sellerA, unique("other")), confirmationIdempotencyKey: "key_main" }), OrderIdempotencyConflictError)); add("Same seller/orderId different key returns typed exists", await error(() => service.persistConfirmedOrder(tenantA, { snapshot: invalid, confirmationIdempotencyKey: "key_other" }), OrderAlreadyExistsError)); const missingSellerId = unique("seller_missing"); add("Missing Seller maps safely", await error(() => service.persistConfirmedOrder(createTenantContext(missingSellerId), { snapshot: snapshot(missingSellerId, unique("order")), confirmationIdempotencyKey: "x" }), OrderSellerNotFoundError));
    const concurrentId = unique("order_concurrent"); const concurrentSnapshot = snapshot(sellerA, concurrentId); const concurrent = await Promise.all([service.persistConfirmedOrder(tenantA, { snapshot: concurrentSnapshot, confirmationIdempotencyKey: "key_concurrent" }), service.persistConfirmedOrder(tenantA, { snapshot: concurrentSnapshot, confirmationIdempotencyKey: "key_concurrent" })]); add("Concurrent same-key same-payload confirmations produce one persisted order", concurrent[0].orderId === concurrentId && concurrent[1].orderId === concurrentId && (await executeDatabaseQuery<{ count: string }>({ text: "SELECT COUNT(*)::text AS count FROM orders WHERE seller_id = $1 AND order_id = $2", values: [sellerA, concurrentId] })).rows[0]?.count === "1");
    const conflictKey = "key_concurrent_conflict"; const conflictOne = snapshot(sellerA, unique("order_conflict")); const conflictTwo = snapshot(sellerA, unique("order_conflict")); const conflictResults = await Promise.allSettled([service.persistConfirmedOrder(tenantA, { snapshot: conflictOne, confirmationIdempotencyKey: conflictKey }), service.persistConfirmedOrder(tenantA, { snapshot: conflictTwo, confirmationIdempotencyKey: conflictKey })]); add("Concurrent same-key different-payload confirmations produce one success and one conflict", conflictResults.filter((entry) => entry.status === "fulfilled").length === 1 && conflictResults.filter((entry) => entry.status === "rejected" && entry.reason instanceof OrderIdempotencyConflictError).length === 1);
    const snapshotFailureId = unique("order_snapshot_rollback"); const snapshotFailureService = new ConfirmedOrderPersistenceService(new PostgreSqlConfirmedOrderRepository({ beforeSnapshotInsert: () => { throw new Error("test snapshot insertion failure"); } })); add("Failed snapshot persistence rolls back root and items", await error(() => snapshotFailureService.persistConfirmedOrder(tenantA, { snapshot: snapshot(sellerA, snapshotFailureId), confirmationIdempotencyKey: "key_snapshot_rollback" }), OrderPersistenceError) && await service.getConfirmedOrder(tenantA, snapshotFailureId) === null);
    const failingId = unique("order_rollback"); const tooLongItem = freeze({ ...snapshot(sellerA, failingId), items: freeze([{ ...snapshot(sellerA, failingId).items[0]!, productName: "x".repeat(256) }]) }); add("Failed item persistence rolls back root and leaves no partial aggregate", await error(() => service.persistConfirmedOrder(tenantA, { snapshot: tooLongItem, confirmationIdempotencyKey: "key_rollback" }), OrderPersistenceError) && await service.getConfirmedOrder(tenantA, failingId) === null);
    const pageTwoId = unique("order_page_two"); await service.persistConfirmedOrder(tenantA, { snapshot: snapshot(sellerA, pageTwoId), confirmationIdempotencyKey: "key_page_two" }); const list = await service.listConfirmedOrders(tenantA, { limit: 1 }); const next = await service.listConfirmedOrders(tenantA, { limit: 10, cursor: list.nextCursor }); add("Confirmed-order list is tenant-scoped and bounded", list.orders.length === 1 && list.orders.every((entry) => entry.customerPhone === "0612345678")); add("Cursor pagination is deterministic", Boolean(list.nextCursor) && next.orders.length >= 1 && next.orders[0]?.orderId !== list.orders[0]?.orderId); add("Cursor pagination does not use OFFSET", !repository.listConfirmedOrders.toString().includes("OFFSET")); add("Historical order does not require a current Catalog foreign key", persisted.items.every((item) => item.productId.startsWith("historical_product")));
    const columns = await executeDatabaseQuery<{ table_name: string; column_name: string }>({ text: "SELECT table_name, column_name FROM information_schema.columns WHERE table_schema = 'public' AND table_name IN ('orders','order_items','confirmed_order_snapshots') ORDER BY table_name, ordinal_position" }); add("Order persistence tables contain expected explicit columns", columns.rows.length === 28); const constraints = await executeDatabaseQuery<{ table_name: string; constraint_name: string }>({ text: "SELECT table_name, constraint_name FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name IN ('orders','order_items','confirmed_order_snapshots')" }); const names = new Set(constraints.rows.map((row) => `${row.table_name}:${row.constraint_name}`)); add("Orders table required constraints exist", ["orders:orders_pkey","orders:orders_seller_fk","orders:orders_idempotency_unique","orders:orders_total_matches_parts"].every((value) => names.has(value))); add("Order-items table required constraints exist", ["order_items:order_items_pkey","order_items:order_items_order_fk","order_items:order_items_position_valid","order_items:order_items_options_array"].every((value) => names.has(value))); add("Snapshot table required constraints exist", ["confirmed_order_snapshots:confirmed_order_snapshots_pkey","confirmed_order_snapshots:confirmed_order_snapshots_order_fk","confirmed_order_snapshots:confirmed_order_snapshots_schema_version_valid"].every((value) => names.has(value))); add("Find/read uses fixed bounded queries rather than per-item reads", !PostgreSqlConfirmedOrderRepository.prototype.findConfirmedOrder.toString().includes("for ("));
  } finally { await cleanup(); const remaining = sellerIds.length ? await executeDatabaseQuery<{ count: string }>({ text: "SELECT COUNT(*)::text AS count FROM orders WHERE seller_id = ANY($1::varchar[])", values: [sellerIds] }) : { rows: [{ count: "0" }] }; add("Test Order rows are cleaned up", remaining.rows[0]?.count === "0"); await closeDatabasePool(); }
  const failed = cases.filter((entry) => !entry.passed); process.stdout.write(`${JSON.stringify({ summary: { total: cases.length, passed: cases.length - failed.length, failed: failed.length }, cases })}\n`); process.exitCode = failed.length ? 1 : 0;
}
main().catch(async () => { await closeDatabasePool(); process.stderr.write('{"ok":false,"message":"Phase 7E order persistence test failed safely."}\n'); process.exitCode = 1; });
